services:
  php:
    image: tugboatqa/php:7-apache
    default: true
    depends: drupal9
    commands:
      init:
        # Install php extensions and mod-rewrite
        - apt-get -y update
        - apt-get install -y libicu-dev
        - apt-get install -y libzip-dev
        - docker-php-ext-configure intl
        - docker-php-ext-install opcache intl zip bcmath gettext pcntl
        - a2enmod headers rewrite

        # Link the document root to the expected path.
        - ln -snf $TUGBOAT_ROOT/httpdocs $DOCROOT

        # Install drush
        - wget -O /usr/local/bin/drush https://github.com/drush-ops/drush-launcher/releases/download/0.6.0/drush.phar
        - chmod +x /usr/local/bin/drush

        # Set memory limit
        - echo "memory_limit = 2G" >> /usr/local/etc/php/conf.d/my-php.ini

        # Update composer
        - composer self-update

        # Install cv
        - curl -LsS https://download.civicrm.org/cv/cv.phar -o /usr/local/bin/cv
        - chmod +x /usr/local/bin/cv

        # Create the Drupal private and public files directories if they aren't
        # already present.
        - mkdir -p "${TUGBOAT_ROOT}/private" "${DOCROOT}/sites/default/files"
      update:
        # Use the tugboat-specific Drupal and CiviCRM settings.
        - cp "${TUGBOAT_ROOT}/.tugboat/settings.local.php" "${DOCROOT}/sites/default/"
        - cp "${TUGBOAT_ROOT}/.tugboat/civicrm.settings.local.php" "${DOCROOT}/sites/default/"

        # Install/update packages managed by composer, including drush.
        #- composer install --optimize-autoloader
        - composer install

        - chgrp -R www-data "${DOCROOT}/sites/default/files"
        - find "${DOCROOT}/sites/default/files" -type d -exec chmod 2775 {} \;
        - find "${DOCROOT}/sites/default/files" -type f -exec chmod 0664 {} \;
      build:
        - composer install
        - cv flush --triggers --cwd="${DOCROOT}"
        - vendor/bin/drush cache:rebuild
        - vendor/bin/drush config:import -y
        - vendor/bin/drush updatedb -y
        - vendor/bin/drush cache:rebuild
  # The 'drupal9' key acts as the hostname.
  drupal9:
    image: tugboatqa/mariadb:10

    # A set of commands to run while building this service
    # commands:
      # Commands that import files, databases,  or other assets. When an
      # existing preview is refreshed, the build workflow starts here,
      # skipping the init step, because the results of that step will
      # already be present.
      # update:
        # Copy a database dump from an external server. The public
        # SSH key found in the Tugboat Repository configuration must be
        # copied to the external server in order to use scp.
        #- scp dev@freeform.dev:~/private/drupal9.sql.gz /tmp/drupal9.sql.gz
        #- zcat /tmp/drupal9.sql.gz | mysql tugboat
        #- rm /tmp/drupal9.sql.gz
  civicrm:
    image: tugboatqa/mariadb:10

    # A set of commands to run while building this service
    #commands:
      # Commands that import files, databases,  or other assets. When an
      # existing preview is refreshed, the build workflow starts here,
      # skipping the init step, because the results of that step will
      # already be present.
      #update:
        #- scp dev@freeform.dev:~/private/civicrm_redacted.sql.gz /tmp/civicrm_redacted.sql.gz
        #- zcat /tmp/civicrm_redacted.sql.gz | mysql tugboat
        #- rm /tmp/civicrm_redacted.sql.gz
